"""added password reset token and expiry columns

Revision ID: 8de4b9eed940
Revises: afe98f119c93
Create Date: 2026-03-22 20:26:19.224290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8de4b9eed940'
down_revision: Union[str, Sequence[str], None] = 'afe98f119c93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('reset_password_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('reset_password_expiry', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'reset_password_expiry')
    op.drop_column('users', 'reset_password_token')
    # ### end Alembic commands ###
