"""add mfa columns to users

Revision ID: 9c3d8cb78527
Revises: d0d44a98426b
Create Date: 2026-03-22 00:30:41.901792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c3d8cb78527'
down_revision: Union[str, Sequence[str], None] = 'd0d44a98426b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('totp_secret', sa.String(), nullable=True))
    op.add_column('users', sa.Column('mfa_enabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'mfa_enabled')
    op.drop_column('users', 'totp_secret')
    # ### end Alembic commands ###
